# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-09 22:16
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=75, validators=[django.core.validators.MinLengthValidator(2)])),
                ('text', models.CharField(max_length=200, validators=[django.core.validators.MinLengthValidator(50)])),
                ('email', models.TextField(validators=[django.core.validators.EmailValidator()])),
                ('number', models.CharField(max_length=16, validators=[django.core.validators.RegexValidator(regex='^\\+?1?\\d{9,15}$')])),
                ('name', models.CharField(max_length=25, validators=[django.core.validators.MinLengthValidator(1)])),
                ('pub_date', models.DateTimeField(blank=True, null=True)),
                ('category', models.CharField(choices=[('es', 'Недвижимость'), ('tr', 'Транспорт'), ('el', 'Електроника'), ('st', 'Вещи'), ('ser', 'Услуги'), (None, '')], default=None, max_length=15)),
                ('vip', models.BooleanField(default=False)),
            ],
        ),
    ]
