# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-11 16:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainsite', '0002_auto_20160110_1642'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='photos',
            field=models.ImageField(default='pics/no_image.png', upload_to='pics/%Y/%m/%d'),
        ),
        migrations.AlterField(
            model_name='item',
            name='category',
            field=models.CharField(choices=[('es', 'Estate'), ('tr', 'Transport'), ('el', 'Electronics'), ('st', 'Stuff'), ('ser', 'Services'), (None, '')], default=None, max_length=15),
        ),
    ]
