# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-11 16:30
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainsite', '0003_auto_20160111_1811'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='photos',
        ),
        migrations.AddField(
            model_name='item',
            name='photo',
            field=models.SlugField(blank=True, max_length=200, validators=[django.core.validators.MinLengthValidator(8)]),
        ),
    ]
