# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-11 16:45
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainsite', '0005_auto_20160111_1835'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='photo',
            field=models.URLField(blank=True, validators=[django.core.validators.MinLengthValidator(8), django.core.validators.URLValidator]),
        ),
    ]
